// Angular/first-project/src/app/cv/cv.component.ts
import { Component } from '@angular/core'
import { WorkExperienceComponent } from '../work-experience/work-experience.component'
import { SkillsComponent } from '../skills/skills.component'
import { LinksComponent } from '../links/links.component'

@Component({
    selector: 'app-cv',
    standalone: true,
    imports: [WorkExperienceComponent, SkillsComponent, LinksComponent],
    templateUrl: './cv.component.html',
    styleUrl: './cv.component.css',
})
export class CvComponent {}

<div>
    <div class="element" style="display: flex; justify-content: center">
        <img src="../../assets/profile_photo.jpg" />
    </div>
    <div class="element">
        <label>Name: </label>
        <p>Vladyslav</p>
    </div>
    <div class="element">
        <label>Surname: </label>
        <p>Karlinskyi</p>
    </div>
    <div class="element">
        <label>Age: </label>
        <p>20</p>
    </div>
    <div class="element">
        <label>Number: </label>
        <p>+380000000000</p>
    </div>
    <div class="element">
        <label>Email: </label>
        <p>test1test.com</p>
    </div>
    <div class="element">
        <label>City: </label>
        <p>Odesa</p>
    </div>
    <div class="element">
        <label>Work experience:</label>
        <app-work-experience></app-work-experience>
    </div>
    <div class="element">
        <label>Skills:</label>
        <app-skills></app-skills>
    </div>
    <div class="element">
        <label>Links:</label>
        <app-links></app-links>
    </div>
</div>

// React/first-app/src/Components/CV/CV.jsx
import profilePicture from '../../assets/profile_photo.jpg';

function Cv() {
    return (
        <div
            style={{
                display: 'flex',
                flexDirection: 'row',
                justifyContent: 'center',
                gap: '10px',
            }}
        >
            <div
                className="element"
                style={{
                    display: 'flex',
                    justifyContent: 'center',
                }}
            >
                <img src={profilePicture} alt="Profile" />
            </div>
            <div className="element">
                <label>Name: </label>
                <p>Vladyslav</p>
            </div>
            <div className="element">
                <label>Surname: </label>
                <p>Karlinskyi</p>
            </div>
            <div className="element">
                <label>Age: </label>
                <p>20</p>
            </div>
            <div className="element">
                <label>Number: </label>
                <p>+380000000000</p>
            </div>
            <div className="element">
                <label>Email: </label>
                <p>test1test.com</p>
            </div>
            <div className="element">
                <label>Country: </label>
                <p>Ukraine</p>
            </div>
            <div className="element">
                <label>City: </label>
                <p>Odesa</p>
            </div>
        </div>
    );
}

export default Cv;
